HenrysBookstore/Controllers/BrowseAuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using HenrysBookstore.Models;

namespace HenrysBookstore.Controllers
{
    public class BrowseAuthorController : Controller
    {
        private BOOKSTOREEntities db = new BOOKSTOREEntities();

        // GET: BrowseAuthor
        public ActionResult BrowseByAuthor()
        {
            BrowseAuthor model = new BrowseAuthor();

            model.AllAuthorOptions = db.AUTHORs.OrderBy(s => s.AUTHOR_FIRST).ToList().Select(s => new SelectListItem
            {
                Text = s.AUTHOR_FIRST + " " + s.AUTHOR_LAST,
                Value = s.AUTHOR_NUM.ToString()
            });

            return PartialView("_FilterAuthor", model);
        }

        [HttpPost]
        public ActionResult BrowseByAuthor(BrowseAuthor model)
        {
            if (string.IsNullOrEmpty(model.AuthorSelected))
            {
                // Throw error pertaining to empty filter criteria
                ModelState.AddModelError("", "Please Select an Author");
            }

            model.AllAuthorOptions = db.AUTHORs.OrderBy(s => s.AUTHOR_FIRST).ToList().Select(s => new SelectListItem
            {
                Text = s.AUTHOR_FIRST + " " + s.AUTHOR_LAST,
                Value = s.AUTHOR_NUM.ToString()
            });

            return PartialView("_FilterAuthor", model);
        }
    }
}

HenrysBookstore/Controllers/BrowseLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HenrysBookstore.Models;

namespace HenrysBookstore.Controllers
{
    public class BrowseLocationController : Controller
    {
        private BOOKSTOREEntities db = new BOOKSTOREEntities();

        // GET: BrowseLocation
        public ActionResult BrowseByLocation()
        {
            BrowseLocation model = new BrowseLocation();

            model.AllLocationOptions = db.BRANCHes.OrderBy(s => s.BRANCH_NAME).ToList().Select(s => new SelectListItem
            {
                Text = s.BRANCH_NAME,
                Value = s.BRANCH_NUM.ToString()
            });

            return PartialView("_FilterLocation",model);
        }

        [HttpPost]
        public ActionResult BrowseByLocation(BrowseLocation model)
        {
            if (string.IsNullOrEmpty(model.LocationSelected))
            {
                // Throw error pertaining to empty filter criteria
                ModelState.AddModelError("", "Please Select a Location");
            }

            model.AllLocationOptions = db.BRANCHes.OrderBy(s => s.BRANCH_NAME).ToList().Select(s => new SelectListItem
            {
                Text = s.BRANCH_NAME,
                Value = s.BRANCH_NUM.ToString()
            });

            return PartialView("_FilterLocation", model);
        }
    }
}

HenrysBookstore/Controllers/BrowsePublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HenrysBookstore.Models;

namespace HenrysBookstore.Controllers
{
    public class BrowsePublisherController : Controller
    {
        private BOOKSTOREEntities db = new BOOKSTOREEntities();

        // GET: BrowsePublisher
        public ActionResult BrowseByPublisher()
        {
            BrowsePublisher model = new BrowsePublisher();

            model.AllPublisherOptions = db.PUBLISHERs.OrderBy(s => s.PUBLISHER_NAME).ToList().Select(s => new SelectListItem
            {
                Text = s.PUBLISHER_NAME,
                Value = s.PUBLISHER_CODE.ToString()
            });

            return PartialView("_FilterPublisher",model);
        }

        [HttpPost]
        public ActionResult BrowseByPublisher(BrowsePublisher model)
        {
            if (string.IsNullOrEmpty(model.PublisherSelected))
            {
                // Throw error pertaining to empty filter criteria
                ModelState.AddModelError("", "Please Select a Publisher");
            }

            model.AllPublisherOptions = db.PUBLISHERs.OrderBy(s => s.PUBLISHER_NAME).ToList().Select(s => new SelectListItem
            {
                Text = s.PUBLISHER_NAME,
                Value = s.PUBLISHER_CODE.ToString()
            });

            return PartialView("_FilterPublisher", model);
        }
    }
}

HenrysBookstore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HenrysBookstore.Models;
using Microsoft.Ajax.Utilities;

namespace HenrysBookstore.Controllers
{
    public class HomeController : Controller
    {
        private BOOKSTOREEntities db = new BOOKSTOREEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BrowseInventory()
        {
            var allInventory = db.BOOKs.OrderBy(x=>x.TITLE).ToList();
            List<INVENTORY> result = new List<INVENTORY>();

            foreach (var item in allInventory)
            {
                INVENTORY model = new INVENTORY();
                model.BOOK_CODE = item.BOOK_CODE;
                result.Add(model);
            }
            
            return View(result);
        }

        public ActionResult BrowseByAuthor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BrowseByAuthor(BrowseAuthor author)
        {
            var uAuthor = author.AuthorSelected;

            var allAuthors = db.AUTHORs.Where(x => x.AUTHOR_NUM.ToString() == uAuthor).ToList();
            List<AUTHOR> result = new List<AUTHOR>();

            foreach (var auth in allAuthors)
            {
                AUTHOR model = new AUTHOR();
                model.AUTHOR_NUM = auth.AUTHOR_NUM;
                model.AUTHOR_FIRST = auth.AUTHOR_FIRST;
                model.AUTHOR_LAST = auth.AUTHOR_LAST;

                var allAuthorBooks = from x in db.WROTEs
                    join y in db.AUTHORs on x.AUTHOR_NUM equals y.AUTHOR_NUM
                    join z in db.BOOKs on x.BOOK_CODE equals z.BOOK_CODE
                    join a in db.PUBLISHERs on z.PUBLISHER_CODE equals a.PUBLISHER_CODE
                    where string.IsNullOrEmpty(uAuthor) || x.AUTHOR_NUM.ToString() == uAuthor
                    select x;

                model.WROTEs = allAuthorBooks.ToList();
                result.Add(model);
            }

            return View(result);
        }

        public ActionResult BrowseByPublisher()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BrowseByPublisher(BrowsePublisher publisher)
        {
            var uPublisher = publisher.PublisherSelected;

            var allPublishers = db.PUBLISHERs.Where(x => x.PUBLISHER_CODE.ToString() == uPublisher).ToList();
            List<PUBLISHER> result = new List<PUBLISHER>();

            foreach (var pub in allPublishers)
            {
                PUBLISHER model = new PUBLISHER();
                model.PUBLISHER_CODE = pub.PUBLISHER_CODE;
                model.PUBLISHER_NAME = pub.PUBLISHER_NAME;

                var allPublisherBooks = from s in db.BOOKs
                    where s.PUBLISHER_CODE == pub.PUBLISHER_CODE
                    where string.IsNullOrEmpty(uPublisher) || s.PUBLISHER_CODE.ToString() == uPublisher
                    select s;

                model.BOOKs = allPublisherBooks.ToList();
                result.Add(model);
            }

            return View(result);
        }

        public ActionResult BrowseByLocation()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BrowseByLocation(BrowseLocation branch)
        {
            var uBranch = branch.LocationSelected;

            var allBranches = db.BRANCHes.Where(x=>x.BRANCH_NUM.ToString() == uBranch).ToList();
            List<BRANCH> result = new List<BRANCH>();

            foreach (var loc in allBranches)
            {
                BRANCH model = new BRANCH();
                model.BRANCH_NUM = loc.BRANCH_NUM;
                model.BRANCH_NAME = loc.BRANCH_NAME;
                model.BRANCH_LOCATION = loc.BRANCH_LOCATION;
                model.NUM_EMPLOYEES = loc.NUM_EMPLOYEES;

                var allBranchInfo = from s in db.INVENTORies
                    join t in db.BRANCHes on s.BRANCH_NUM equals t.BRANCH_NUM
                    join u in db.BOOKs on s.BOOK_CODE equals u.BOOK_CODE
                    where string.IsNullOrEmpty(uBranch) || s.BRANCH_NUM.ToString() == uBranch
                    select s;

                model.INVENTORies = allBranchInfo.ToList();
                result.Add(model);
            }

            return View(result);
        }

        public ActionResult ContactManagement(Feedback model)
        {
            ModelState.Clear();

            model.AllBranchOptions = db.BRANCHes.OrderBy(s => s.BRANCH_NAME).ToList().Select(s => new SelectListItem
            {
                Text = s.BRANCH_NAME,
                Value = s.BRANCH_NAME.ToString()
            });

            return View(model);
        }

        [HttpPost]
        public JsonResult Feedback(Feedback model)
        {
            ViewBag.Title = "Feedback sent";

            return Json(model);
        }
    }
}

HenrysBookstore/Views/Home/BrowseByAuthor.cshtml
@using System.Activities.Statements
@using System.Globalization
@using HenrysBookstore.Models;
@model IEnumerable<AUTHOR>

@{
    ViewBag.Title = "Browse By Author";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_SideNavigation")
    </div>
    <div class="col-md-9">
        <h2>@ViewBag.Title</h2>
        @Html.Action("BrowseByAuthor", "BrowseAuthor")

        @if (Model != null)
        {
            <br/>

            foreach (var allAuthors in Model)
            {
                <table class="results-tbl">
                    <tr>
                        <th>Book Code</th>
                        <th>Title</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Paperback?</th>
                        <th>Publisher</th>
                    </tr>

                    @foreach (var singlebook in allAuthors.WROTEs)
                    {
                        var curBookCode = singlebook.BOOK_CODE;
                        var curTitle = singlebook.BOOK.TITLE;
                        var curType = singlebook.BOOK.TYPE;
                        var curPrice = Convert.ToDecimal(singlebook.BOOK.PRICE).ToString("0.00");
                        var curPaperback = singlebook.BOOK.PAPERBACK;
                        var curPublisher = singlebook.BOOK.PUBLISHER.PUBLISHER_NAME;

                        var formattedPaperback = "";

                        if (curPaperback == "1")
                        {
                            formattedPaperback = "True";
                        }
                        else
                        {
                            formattedPaperback = "False";
                        }

                        <tr>
                            <td>@curBookCode</td>
                            <td>@CultureInfo.CurrentCulture.TextInfo.ToTitleCase(curTitle)</td>
                            <td>@curType</td>
                            <td>$@curPrice</td>
                            <td>@formattedPaperback</td>
                            <td>@curPublisher</td>
                        </tr>

                    }
                </table>
            }
        }
    </div>
</div>

HenrysBookstore/Views/Home/BrowseByLocation.cshtml
@using System.Globalization
@using HenrysBookstore.Models;
@model IEnumerable<BRANCH>

@{
    ViewBag.Title = "Browse By Location";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_SideNavigation")
    </div>
    <div class="col-md-4">
        <h2>@ViewBag.Title</h2>
        @Html.Action("BrowseByLocation", "BrowseLocation")
        
        @if (Model != null)
        {
            <br/>
            <table class="results-tbl">
                @foreach (var branch in Model)
                {
                    var curNum = branch.BRANCH_NUM;
                    var curName = branch.BRANCH_NAME;
                    var curLocation = branch.BRANCH_LOCATION;
                    var curNumEmp = branch.NUM_EMPLOYEES;

                    <tr>
                        <th>Branch Number</th>
                        <td>@curNum</td>
                    </tr>
                    <tr>
                        <th>Branch Name</th>
                        <td>@CultureInfo.CurrentCulture.TextInfo.ToTitleCase(@curName)</td>
                    </tr>
                    <tr>
                        <th>Branch Location</th>
                        <td>@curLocation</td>
                    </tr>
                    <tr>
                        <th>Number of Employees</th>
                        <td>@curNumEmp</td>
                    </tr>
                }

            </table>
        }
    </div>
    <div class="col-md-5">
        @if (Model != null)
        {
            <br />
            <table class="results-tbl">
                @foreach (var inv in Model)
                {
                    <tr>
                        <th>Title</th>
                        <th>Quantity on Hand</th>
                    </tr>

                    foreach (var book in inv.INVENTORies.OrderBy(x=>x.BOOK.TITLE))
                    {
                        var curTitle = book.BOOK.TITLE;
                        var curQntyOnHand = book.ON_HAND;

                        <tr>
                            <td>@CultureInfo.CurrentCulture.TextInfo.ToTitleCase(@curTitle)</td>
                            <td>@curQntyOnHand</td>
                        </tr>
                    }
                }
            </table>
        }
    </div>
</div>

HenrysBookstore/Views/Home/BrowseByPublisher.cshtml
@using System.Globalization
@using HenrysBookstore.Models;
@model IEnumerable<PUBLISHER>

@{
    ViewBag.Title = "Browse By Publisher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_SideNavigation")
    </div>
    <div class="col-md-9">
        <h2>@ViewBag.Title</h2>
        @Html.Action("BrowseByPublisher", "BrowsePublisher")

        @if (Model != null)
        {
            <br/>


            foreach (var pub in Model)
            {
                <table class="results-tbl">
                    <tr>
                        <th>Book Code</th>
                        <th>Title</th>
                        <th>Type</th>
                        <th>Price</th>
                        <th>Paperback?</th>
                    </tr>

                    @foreach (var allBooks in pub.BOOKs)
                    {
                        var curBookCode = allBooks.BOOK_CODE;
                        var curTitle = allBooks.TITLE;
                        var curType = allBooks.TYPE;
                        var curPrice = Convert.ToDecimal(allBooks.PRICE).ToString("0.00");
                        var curPaperback = allBooks.PAPERBACK;
                        var formattedPaperback = "";

                        if (curPaperback == "1")
                        {
                            formattedPaperback = "True";
                        }
                        else
                        {
                            formattedPaperback = "False";
                        }

                        <tr>
                            <td>@curBookCode</td>
                            <td>@CultureInfo.CurrentCulture.TextInfo.ToTitleCase(curTitle)</td>
                            <td>@curType</td>
                            <td>$@curPrice</td>
                            <td>@formattedPaperback</td>
                        </tr>
                    }
                </table>
            }
        }
    </div>
</div>

HenrysBookstore/Views/Home/BrowseInventory.cshtml
@using HenrysBookstore.Models;
@model IEnumerable<INVENTORY>

@{
    ViewBag.Title = "Browse Inventory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_SideNavigation")
    </div>
    <div class="col-md-9">
        <h2>@ViewBag.Title</h2>
        @foreach (var allBooks in Model)
        {
            string curBook = allBooks.BOOK_CODE;

            <img class="book-thumb" src="~/Content/images/@curBook/thumb.jpg"/>
        }
    </div>
</div>

HenrysBookstore/Views/Home/ContactManagement.cshtml
@using System.ComponentModel.DataAnnotations
@model HenrysBookstore.Models.Feedback
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        function SendFeedback(formData) {
            var target = $("#feedbackForm");

            if (formData && formData.fname != null && formData.lname != null && 
                formData.email != null && formData.confirmemail != null && 
                formData.phonenumber != null && formData.branchname != null && 
                formData.comments != null) {
                target.empty();
                target.append("<p><strong>--- FEEDBACK RECEIVED ---</strong></p>" + 
                    "First Name: " + formData.fname + "<br />" + 
                    "Last Name: " + formData.lname + "<br />" + 
                    "Email: " + formData.email + "<br />" + 
                    "Phone Number: " + formData.phonenumber + "<br />" + 
                    "Branch Name: " + formData.branchname + "<br />" + 
                    "Comments: " + formData.comments);
            }
            else {
                target.append("ERROR!  Please check your entry.  No information has been sent.");
            }
        }
    </script>
}

@{
    ViewBag.Title = "Contact Management";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3">
        @Html.Partial("_SideNavigation")
    </div>
    <div class="col-md-9">
        <h2>@ViewBag.Title</h2>
        <div id="loading" style="display: none">
            <p>
                Thank you for sharing your comments with Henry's Bookstore <br />
                Management.  We will be in touch with you shortly via email.
            </p>
        </div>
        <div id="feedbackForm">
            @using (Ajax.BeginForm("Feedback",
                "Home",
                new AjaxOptions
                {
                    HttpMethod = "Post",
                    InsertionMode = InsertionMode.Replace,
                    LoadingElementId = "loading",
                    LoadingElementDuration = 10000,
                    OnSuccess = "SendFeedback",
                }))

            {
            <table class="fbForm">
                @Html.ValidationSummary(false)
                <tr>
                    <td>First Name</td>
                    <td>@Html.TextBoxFor(s => s.fname)</td>
                </tr>
                <tr>
                    <td>Last Name</td>
                    <td>@Html.TextBoxFor(s => s.lname)</td>
                </tr>
                <tr>
                    <td>Email Address</td>
                    <td>@Html.TextBoxFor(s => s.email)</td>
                </tr>
                <tr>
                    <td>Confirm Email Address</td>
                    <td>@Html.TextBoxFor(s => s.confirmemail)</td>
                </tr>
                <tr>
                    <td>Phone Number</td>
                    <td>@Html.TextBoxFor(s => s.phonenumber)</td>
                </tr>
                <tr>
                    <td>Branch</td>
                    <td>@Html.DropDownListFor(s => s.branchname, Model.AllBranchOptions, "Please Choose a Location")</td>
                </tr>
                <tr>
                    <td>Comments</td>
                    <td>@Html.TextAreaFor(s => s.comments)</td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="reset" value="Reset" /><input type="submit" value="Save" /></td>
                </tr>
            </table>
            }
        </div>
    </div>
</div>

HenrysBookstore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div id="home-nav" class="col-md-12">
        <a href="@Url.Action("BrowseInventory", "Home")">
            <div class="nav-card col-md-6">
                <p>Browse Inventory</p>
                <img src="~/Content/images/inventory.jpg" />

            </div>
        </a>
        <a href="@Url.Action("BrowseByAuthor", "Home")">
            <div class="nav-card col-md-6">
                <p>Browse by Author</p>
                <img src="~/Content/images/author.jpg" />

            </div>
        </a>
        <a href="@Url.Action("BrowseByPublisher", "Home")">
            <div class="nav-card col-md-6">
                <p>Browse by Publisher</p>
                <img src="~/Content/images/publisher.jpg" />

            </div>
        </a>
        <a href="@Url.Action("BrowseByLocation", "Home")">
            <div class="nav-card col-md-6">
                <p>Browse by Location</p>
                <img src="~/Content/images/bookstore.jpg" />

            </div>
        </a>
    </div>
</div>